[package]
name = "axum_csrf"
version = "0.3.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a CSRF (Cross-Site Request Forgery) protection layer."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_csrf"
keywords = ["Axum", "CSRF", "Cookies"]
repository = "https://github.com/AscendingCreations/AxumCSRF"

[dependencies]
axum = "0.5"
async-trait = "0.1"
rand = "0.8"
bcrypt = "0.12"
time = { version = "0.3", default-features = false, features = ["std"] }
base64 = "0.13"
cookie = { version = "0.16", features = [
    "percent-encode",
    "signed",
    "private",
] }
