[package]
name = "axum_csrf"
version = "0.5.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a CSRF (Cross-Site Request Forgery) protection layer."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_csrf"
keywords = ["Axum", "CSRF", "Cookies"]
repository = "https://github.com/AscendingCreations/AxumCSRF"

[dependencies]
axum-core = "0.3.0-rc.1"
http = "0.2.8"
async-trait = "0.1.57"
rand = "0.8.5"
bcrypt = "0.13.0"
time = { version = "0.3.13", default-features = false, features = ["std"] }
base64 = "0.13.0"
cookie = { version = "0.16.0", features = [
    "percent-encode",
    "signed",
    "private",
] }

[dev-dependencies]
anyhow = "1.0.60"
axum = "0.6.0-rc.1"