[package]
name = "axum_csrf"
version = "0.1.2"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a CSRF (Cross-Site Request Forgery) protection layer. You must also include Tower_cookies in order to use this Library."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_csrf"
keywords = ["Axum", "Tower", "CSRF", "Cookies"]
repository = "https://github.com/AscendingCreations/AxumCSRF"

[dependencies]
axum = "0.4"
async-trait = "0.1.51"
rand = "0.8"
tower-cookies = { version = "0.3", features = ["signed"] }
bcrypt = "0.9"
time = { version = "0.2.11", default-features = false, features = ["std"] }
base64 = "0.13.0"
cookie = { version = "0.15", features = ["percent-encode"] }
