[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum_csrf = "0.6.0"
axum = "0.6.12"
serde = "1.0.159"
tokio = { version = "1.27.0", features = ["full"] }
askama = "0.12.0"
askama_axum = "0.3.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"